import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/jamalbalya/jemz-vault-assistant
*/
`;

const prod = process.argv[2] === 'production';

/** Shared esbuild options for both the JS bundle and the CSS bundle. */
const shared = {
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
};

const jsContext = await esbuild.context({
	...shared,
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	outfile: 'main.js',
});

// Styles live as modular CSS under src/ui/styles and are bundled into the single
// styles.css file Obsidian loads alongside main.js.
const cssContext = await esbuild.context({
	...shared,
	entryPoints: ['src/ui/styles/main.css'],
	outfile: 'styles.css',
	loader: { '.css': 'css' },
});

if (prod) {
	await jsContext.rebuild();
	await cssContext.rebuild();
	await jsContext.dispose();
	await cssContext.dispose();
	process.exit(0);
} else {
	await jsContext.watch();
	await cssContext.watch();
}
