/**
 * Every user-facing string in the plugin (addendum E-08).
 *
 * Keeping them in one module means a future translation only has to supply a second object
 * of the same shape. Copy follows Obsidian's style guide: sentence case, imperative verbs,
 * no jargon.
 */

export const STRINGS = {
	common: {
		cancel: 'Cancel',
		close: 'Close',
		confirm: 'Confirm',
		apply: 'Apply changes',
		done: 'Done',
		open: 'Open',
		openInNewPane: 'Open in new pane',
		copyLink: 'Copy link',
		pin: 'Pin',
		unpin: 'Unpin',
		delete: 'Delete',
		archive: 'Archive',
		rename: 'Rename',
		retry: 'Retry',
		details: 'Details',
		ignore: 'Ignore',
		save: 'Save',
		create: 'Create',
		back: 'Back',
		next: 'Next',
		previous: 'Previous',
		skip: 'Skip',
		loading: 'Loading…',
		search: 'Search',
		noResults: 'No results',
		of: 'of',
	},

	plugin: {
		name: 'Jemz Vault Assistant',
		ribbonTooltip: 'Open Jemz Vault Assistant',
		loadFailed: 'Jemz Vault Assistant failed to load. See the developer console for details.',
	},

	commands: {
		openDashboard: 'Open dashboard',
		quickCapture: 'Quick capture',
		startTriage: 'Start triage',
		runHealthScan: 'Run health scan',
		viewInbox: 'View inbox',
		viewHealth: 'View health',
		viewFind: 'View find',
		searchNotes: 'Search notes',
		toggleStatusBar: 'Toggle status bar',
		restoreLastBackup: 'Restore last fix backup',
	},

	dashboard: {
		title: 'Jemz Vault Assistant',
		tabInbox: 'Inbox',
		tabHealth: 'Health',
		tabFind: 'Find',
		statsInbox: (count: number): string => `inbox ${count}`,
		statsHealth: (score: number): string => `health ${score}`,
		moduleDisabled: (module: string): string =>
			`The ${module} module is turned off. Enable it in settings to use this tab.`,
		enableInSettings: 'Open settings',
	},

	statusBar: {
		tooltip: 'Jemz Vault Assistant — open dashboard',
		text: (inbox: number, health: number): string => `📥 ${inbox} | 🏥 ${health}`,
		hidden: 'Status bar item hidden',
		shown: 'Status bar item shown',
	},

	capture: {
		modalTitle: 'Quick capture',
		titleLabel: 'Title',
		titlePlaceholder: 'What is on your mind?',
		bodyLabel: 'Body',
		bodyPlaceholder: 'Optional details. Markdown works here.',
		tagsLabel: 'Tags',
		tagsPlaceholder: 'Add a tag and press Enter',
		typeLabel: 'Type',
		sourceLabel: 'Source',
		sourcePlaceholder: 'https://example.com',
		projectLabel: 'Project',
		projectNone: 'No project',
		submit: 'Capture',
		success: 'Captured to inbox',
		failed: 'Could not capture the note',
		invalidUrl: 'That does not look like a valid URL',
		untitledPrefix: 'Untitled',
		folderMissingTitle: 'Create inbox folder?',
		folderMissingBody: (folder: string): string =>
			`The folder "${folder}" does not exist yet. Create it now and use it for captures?`,
		folderCreated: (folder: string): string => `Created "${folder}"`,
		readOnly: 'The vault is read-only, so the note could not be saved.',
	},

	inbox: {
		heading: 'Inbox',
		itemCount: (count: number): string => (count === 1 ? '1 item' : `${count} items`),
		startTriage: 'Start triage',
		emptyTitle: 'Inbox zero!',
		emptyBody: 'Capture something new?',
		emptyAction: 'Quick capture',
		sortNewest: 'Newest first',
		sortOldest: 'Oldest first',
		page: (current: number, total: number): string => `Page ${current} of ${total}`,
		actions: {
			open: 'Open',
			process: 'Process',
			convertToTask: 'Task',
			move: 'Move',
			addTag: 'Tag',
			link: 'Link',
			archive: 'Archive',
			delete: 'Delete',
		},
		processed: 'Marked as processed',
		convertedToTask: 'Converted to a task',
		moved: (folder: string): string => `Moved to "${folder}"`,
		tagged: (tag: string): string => `Added #${tag}`,
		linked: (title: string): string => `Linked to "${title}"`,
		archived: 'Moved to archive',
		deleted: 'Moved to trash',
		deleteConfirmTitle: 'Delete this note?',
		deleteConfirmBody: (title: string): string =>
			`"${title}" will be moved to the trash. Archiving keeps it in the vault instead.`,
		deleteConfirmCta: 'Move to trash',
		archiveInstead: 'Archive instead',
		actionFailed: 'That action could not be completed',
		selectFolder: 'Move to folder',
		selectNote: 'Link to note',
		addTagPrompt: 'Add a tag',
	},

	triage: {
		title: 'Triage',
		progress: (current: number, total: number): string => `Item ${current} of ${total}`,
		hintExit: 'Esc to exit',
		nothingToTriage: 'There is nothing in the inbox to triage.',
		summaryTitle: 'Triage session summary',
		summaryProcessed: 'Processed',
		summaryConverted: 'Converted to task',
		summaryMoved: 'Moved',
		summaryArchived: 'Archived',
		summaryDeleted: 'Deleted',
		summarySkipped: 'Skipped',
		summaryRemaining: 'Remaining in inbox',
		continueTriaging: 'Continue triaging',
		shortcuts: {
			process: 'P / Enter',
			task: 'T',
			move: 'M',
			tag: 'G',
			link: 'L',
			archive: 'A',
			delete: 'D',
			skip: 'S / →',
			previous: '←',
			exit: 'Esc',
		},
	},

	health: {
		heading: 'Vault health',
		score: 'Health score',
		scoreExcellent: 'Excellent',
		scoreGood: 'Good',
		scoreFair: 'Needs attention',
		scorePoor: 'Poor',
		rescan: 'Rescan',
		settings: 'Settings',
		lastScan: (when: string): string => `Last scan ${when}`,
		neverScanned: 'This vault has not been scanned yet.',
		scanCta: 'Run a health scan',
		scanning: (processed: number, total: number): string =>
			`Scanning… ${processed}/${total} files`,
		scanComplete: (issues: number): string =>
			issues === 0 ? 'No issues found' : `Found ${issues} issues`,
		scanFailed: 'The health scan failed',
		healthyTitle: 'Your vault is healthy',
		healthyBody: 'Nothing needs fixing right now.',
		issueCount: (count: number): string => (count === 1 ? '1 issue' : `${count} issues`),
		selectAll: 'Select all',
		clearSelection: 'Clear selection',
		fixSelected: 'Fix selected',
		ignoreSelected: 'Ignore selected',
		types: {
			'broken-link': 'Broken links',
			'orphan-note': 'Orphan notes',
			'empty-note': 'Empty notes',
			'unused-attachment': 'Unused attachments',
			'duplicate-title': 'Duplicate titles',
			'tag-inconsistency': 'Tag inconsistencies',
			'missing-metadata': 'Missing metadata',
			'large-file': 'Large files',
			'corrupted-frontmatter': 'Corrupted frontmatter',
		},
		typeDescriptions: {
			'broken-link': 'Links pointing at notes that do not exist.',
			'orphan-note': 'Notes with no links in and no links out.',
			'empty-note': 'Notes with little or no content.',
			'unused-attachment': 'Attachments no note references.',
			'duplicate-title': 'Notes that share a title.',
			'tag-inconsistency': 'Tags that look like misspellings of each other.',
			'missing-metadata': 'Notes missing required frontmatter properties.',
			'large-file': 'Files above the size threshold.',
			'corrupted-frontmatter': 'Notes whose frontmatter could not be parsed.',
		},
		fixes: {
			createNote: 'Create note',
			replaceLink: 'Replace with…',
			removeLink: 'Remove link',
			addTag: 'Add tag',
			moveToArchive: 'Move to archive',
			trash: 'Move to trash',
			deletePermanently: 'Delete permanently',
			mergeTags: 'Merge tags',
			rename: 'Rename',
			addMetadata: 'Add properties',
			openBoth: 'Open both',
		},
	},

	preview: {
		title: 'Review changes',
		summary: (files: number, changes: number): string =>
			`${changes} change${changes === 1 ? '' : 's'} across ${files} file${files === 1 ? '' : 's'}`,
		warning: 'These edits modify files in your vault. Review the list below before applying.',
		destructiveWarning: 'This permanently deletes data and cannot be undone from the backup.',
		backupLocation: (path: string): string => `A backup will be saved to ${path}`,
		noBackup: 'No backup could be created — apply at your own risk.',
		confirmDestructiveTitle: 'Permanently delete?',
		confirmDestructiveBody:
			'These files will be removed for good. Moving them to the trash is safer and is usually what you want.',
		confirmDestructiveCta: 'Delete permanently',
		applying: (done: number, total: number): string => `Applying… ${done}/${total}`,
		resultTitle: 'Changes applied',
		resultApplied: (count: number): string => `${count} applied`,
		resultSkipped: (count: number): string => `${count} skipped`,
		resultFailed: (count: number): string => `${count} failed`,
		skippedConflict: 'Skipped — the file changed after the preview was built',
		skippedUnreadable: 'Skipped — the file could not be read',
		restoreHint: 'Use "Restore last fix backup" to undo this batch.',
	},

	backup: {
		created: (path: string): string => `Backup saved to ${path}`,
		failed: 'The backup could not be created, so no changes were applied.',
		restoreConfirmTitle: 'Restore last fix backup?',
		restoreConfirmBody: (when: string, files: number): string =>
			`This restores ${files} file${files === 1 ? '' : 's'} from the backup taken ${when}. Newer edits to those files will be replaced.`,
		restored: (count: number): string => `Restored ${count} file${count === 1 ? '' : 's'}`,
		none: 'There is no fix backup to restore.',
		restoreFailed: 'The backup could not be restored',
	},

	find: {
		heading: 'Find',
		searchPlaceholder: 'Search notes…',
		resultCount: (count: number): string => (count === 1 ? '1 result' : `${count} results`),
		searching: 'Searching…',
		emptyTitle: 'No notes match',
		emptyBody: 'Try a shorter search or remove a filter.',
		savedViews: 'Saved views',
		newView: 'New view',
		editView: 'Edit view',
		deleteView: 'Delete view',
		deleteViewConfirm: (name: string): string => `Delete the saved view "${name}"?`,
		viewNameLabel: 'View name',
		viewIconLabel: 'Icon',
		viewLogicLabel: 'Match',
		viewLogicAnd: 'All filters',
		viewLogicOr: 'Any filter',
		sortLabel: 'Sort by',
		addFilter: 'Add filter',
		removeFilter: 'Remove filter',
		copiedLink: 'Link copied',
		viewSaved: 'View saved',
		builtInViews: {
			recent: 'Recent notes',
			editedToday: 'Edited today',
			inbox: 'Inbox',
			orphans: 'Orphan notes',
			noTags: 'Notes without tags',
			unlinkedMentions: 'Unlinked mentions',
		},
		fields: {
			keyword: 'Keyword',
			tag: 'Tag',
			folder: 'Folder',
			frontmatter: 'Property',
			created: 'Created date',
			modified: 'Modified date',
			status: 'Status',
			type: 'Type',
			'has-backlinks': 'Has backlinks',
			'has-attachments': 'Has attachments',
			'word-count': 'Word count',
		},
		operators: {
			contains: 'contains',
			'not-contains': "doesn't contain",
			'starts-with': 'starts with',
			'ends-with': 'ends with',
			is: 'is',
			'is-not': 'is not',
			'is-in': 'is in',
			'is-not-in': 'is not in',
			before: 'before',
			after: 'after',
			between: 'between',
			yes: 'yes',
			no: 'no',
			'greater-than': 'greater than',
			'less-than': 'less than',
		},
		sortFields: {
			relevance: 'Relevance',
			created: 'Created',
			modified: 'Modified',
			title: 'Title',
			'word-count': 'Word count',
		},
	},

	contextual: {
		onThisDay: 'On this day',
		onThisDayEmpty: 'No notes from this day in previous years.',
		yearsAgo: (years: number): string => (years === 1 ? '1 year ago' : `${years} years ago`),
		unlinkedMentions: 'Unlinked mentions',
		unlinkedMentionsEmpty: 'No unlinked mentions found.',
		convertToLink: 'Convert to link',
		converted: 'Converted to a link',
		staleNotes: 'Stale notes',
		staleNotesEmpty: 'Nothing has gone stale. Nice.',
		staleFor: (days: number): string => `${days} days`,
		similarNotes: 'Similar notes',
		similarNotesEmpty: 'No similar notes found.',
		similarity: (score: number): string => `${Math.round(score * 100)}% similar`,
		linkThem: 'Link them',
		sharedTags: 'Shared tags',
		sharedLinks: 'Shared links',
	},

	settings: {
		general: 'General',
		captureInbox: 'Capture and inbox',
		vaultHealth: 'Vault health',
		smartRetrieval: 'Smart retrieval',
		analytics: 'Analytics',
		about: 'About',
		modulesHeading: 'Modules',
		moduleCapture: 'Capture and inbox triage',
		moduleCaptureDesc: 'Quick capture, the inbox list, and triage mode.',
		moduleHealth: 'Vault health and maintenance',
		moduleHealthDesc: 'Scanning for vault decay and applying safe fixes.',
		moduleRetrieval: 'Smart retrieval and recall',
		moduleRetrievalDesc: 'Search, saved views, and contextual note discovery.',
		showRibbon: 'Show ribbon icon',
		showRibbonDesc: 'Display the compass icon in the left ribbon.',
		showStatusBar: 'Show status bar item',
		showStatusBarDesc: 'Display inbox count and health score in the status bar.',
		logLevel: 'Log level',
		logLevelDesc: 'How much detail the plugin writes to the developer console.',
		inboxFolder: 'Inbox folder',
		inboxFolderDesc: 'Where quick captures are saved.',
		archiveFolder: 'Archive folder',
		archiveFolderDesc: 'Where archived notes are moved.',
		attachmentArchiveFolder: 'Attachment archive folder',
		attachmentArchiveFolderDesc: 'Where archived attachments are moved.',
		defaultTags: 'Default tags',
		defaultTagsDesc: 'Comma separated tags added to every capture.',
		defaultType: 'Default type',
		defaultTypeDesc: 'Preselected type in the quick capture modal.',
		autoCreateFolders: 'Create folders automatically',
		autoCreateFoldersDesc: 'Create the inbox and archive folders when they are missing.',
		inboxPageSize: 'Items per page',
		inboxPageSizeDesc: 'How many inbox items to show at once.',
		scanFrequency: 'Scan frequency',
		scanFrequencyDesc: 'How often a background health scan runs.',
		autoScanOnStartup: 'Scan on startup',
		autoScanOnStartupDesc: 'Run a full scan when Obsidian starts. Slower startup.',
		excludedFolders: 'Excluded folders',
		excludedFoldersDesc: 'Comma separated folders to leave out of health scans.',
		excludedTags: 'Excluded tags',
		excludedTagsDesc: 'Comma separated tags to leave out of health scans.',
		excludedExtensions: 'Excluded file types',
		excludedExtensionsDesc: 'Comma separated extensions to leave out, without the dot.',
		excludeInbox: 'Skip the inbox',
		excludeInboxDesc:
			'Leave unprocessed captures out of health scans. They are not vault decay yet.',
		excludeArchived: 'Skip archived notes',
		excludeArchivedDesc: 'Leave notes with status "archived" out of health scans.',
		requiredFields: 'Required properties',
		requiredFieldsDesc: 'Comma separated frontmatter keys every note should have.',
		largeFileThreshold: 'Large file threshold (MB)',
		largeFileThresholdDesc: 'Files above this size are reported.',
		scoreWeights: 'Score weights',
		scoreWeightsDesc: 'Points subtracted per issue, and the cap for each category.',
		weightPer: 'per issue',
		weightMax: 'max',
		detectorsHeading: 'Detectors',
		detectorsDesc: 'Turn individual checks on or off.',
		ignoreListsHeading: 'Ignore lists',
		ignoreListsDesc: 'Issues you chose to ignore, excluded from every future scan.',
		ignoredItems: (count: number): string =>
			count === 1 ? '1 ignored item' : `${count} ignored items`,
		clearIgnored: 'Clear',
		staleThreshold: 'Stale after (days)',
		staleThresholdDesc: 'Notes untouched for this long appear in Stale notes.',
		fuzzySensitivity: 'Fuzzy sensitivity',
		fuzzySensitivityDesc: 'Higher tolerates more typos in search.',
		resultsPerPage: 'Results per page',
		resultsPerPageDesc: 'How many search results to show at once.',
		excludeArchivedFromViews: 'Hide archived notes',
		excludeArchivedFromViewsDesc: 'Keep archived notes out of the built-in saved views.',
		analyticsEnabled: 'Share anonymous usage data',
		analyticsEnabledDesc:
			'Off by default. Counts feature usage only — never note content, names, tags, or paths. Nothing leaves your device unless you turn this on.',
		analyticsView: 'View collected data',
		analyticsDelete: 'Delete collected data',
		analyticsDeleted: 'Analytics data deleted',
		analyticsEmpty: 'No analytics data has been collected.',
		aboutVersion: 'Version',
		aboutRepository: 'Repository',
		aboutIssues: 'Report an issue',
		aboutChangelog: 'Changelog',
		actionLogHeading: 'Action log',
		actionLogDesc: 'The last 100 actions this plugin performed.',
		actionLogEmpty: 'No actions recorded yet.',
		actionLogClear: 'Clear log',
		actionLogCleared: 'Action log cleared',
		resetSettings: 'Reset all settings',
		resetSettingsDesc: 'Restore every setting to its default value.',
		resetConfirmTitle: 'Reset all settings?',
		resetConfirmBody:
			'Every setting returns to its default. Saved views, ignore lists, and the action log are cleared.',
		saved: 'Settings saved',
	},

	onboarding: {
		title: 'Welcome to Jemz Vault Assistant',
		intro: 'Three things this plugin does. It takes about a minute to get going.',
		step1Title: '1. Capture',
		step1Body: 'Press the capture command to drop a thought into your inbox in seconds.',
		step2Title: '2. Health',
		step2Body:
			'Scan the vault for broken links, orphans, and other decay — then fix it safely.',
		step3Title: '3. Find',
		step3Body: 'Search and saved views find notes without you remembering where they live.',
		createFoldersTitle: 'Create the default folders?',
		createFoldersBody: (inbox: string, archive: string): string =>
			`This creates "${inbox}" for captures and "${archive}" for archived notes. Nothing else is touched.`,
		createFolders: 'Create folders',
		skipFolders: 'Not now',
		foldersCreated: 'Default folders created',
		openDocs: 'Read the docs',
		finish: 'Get started',
	},

	errors: {
		vaultReadOnly: 'The vault is read-only, so nothing was changed.',
		fileNotFound: (path: string): string => `Could not find "${path}"`,
		folderNotFound: (folder: string): string => `The folder "${folder}" does not exist.`,
		createFolder: 'Create it',
		chooseFolder: 'Choose another',
		readFailed: (path: string): string => `Could not read "${path}"`,
		writeFailed: (path: string): string => `Could not write "${path}"`,
		unexpected: 'Something went wrong. See the developer console for details.',
		notConfirmed: 'Changes were not applied because they were not confirmed.',
	},
} as const;

/** Shape of the string table, so a translation can be checked at compile time. */
export type StringTable = typeof STRINGS;
